# NumPy Basics: Arrays and Vectorized Computation

In [1]:
%matplotlib inline

/home/henry/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## The NumPy ndarray: a multidimensional array object

In [3]:
data = randn(2, 3)             #随机生成一个形状为(2, 3)数组对象

In [7]:
data

array([[-1.9535, -1.6033, -1.4766],
       [ 0.1911,  0.7021,  0.6682]])

In [9]:
data * 10

array([[-19.5353, -16.0331, -14.7665],
       [  1.9112,   7.0206,   6.6817]])

In [10]:
data + data

array([[-3.9071, -3.2066, -2.9533],
       [ 0.3822,  1.4041,  1.3363]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype             #data元素类型

dtype('float64')

### Creating ndarrays

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim           #数组的维数

2

In [18]:
arr2.shape

(2, 4)

In [ ]:
arr1.dtype
arr2.dtype

In [19]:
np.zeros(10)          #制定数组长度

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [20]:
np.zeros((2,3))     #制定数组形状

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.empty((2,3,2))   #数组形状(2,3,2),没有指定初始值

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [22]:
np.arange(15)             #类似与Python的range() ,但这里产生一个array对象

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays
### astype function

In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)                #数组元素类型转换
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [30]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [28]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [35]:
empty_uint32 = np.empty(8, dtype='u4')           #u无符号32位整数类型
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Operations between arrays and scalars

In [36]:
#Arithmetic operations with scalars
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [37]:
1 / arr
arr ** 0.5

array([[ 1.    ,  1.4142,  1.7321],
       [ 2.    ,  2.2361,  2.4495]])

### Basic indexing and slicing

In [49]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr_slice = arr[5:8]                #arr的第5,6,7个元素与arr_slice的第0,1,2个元素是共用的
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [53]:
print arr[5] is arr_slice[0]

False


In [56]:
arr
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[0][2]
arr2d[0, 2]

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

In [ ]:
arr3d[0]

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

In [ ]:
arr3d[1, 0]

#### Indexing with slices

In [ ]:
arr[1:6]

In [ ]:
arr2d
arr2d[:2]

In [ ]:
arr2d[:2, 1:]

In [ ]:
arr2d[1, :2]
arr2d[2, :1]

In [ ]:
arr2d[:, :1]

In [60]:
arr2d[:2, 1:] = 0
arr2d[:2, 1:]

array([[0, 0],
       [0, 0]])

### Boolean indexing

In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [67]:
data

array([[-0.1284,  0.9638,  2.26  ,  0.7324],
       [-0.3177,  2.3068, -0.5007,  0.1574],
       [ 0.3335,  0.8099, -1.6199,  1.3251],
       [-0.8193, -0.4379, -0.4942, -0.8167],
       [-0.7566, -1.0517,  0.1802,  0.5792],
       [-1.9211, -0.5978, -0.0366,  1.264 ],
       [-1.3856, -1.4865, -1.1779, -1.3247]])

In [65]:
names == 'Bob'         #将“Bob"与names中每个元素比较

array([ True, False, False,  True, False, False, False], dtype=bool)

In [66]:
#使用布尔数组索引数组，布尔数组长度7，索引data的维长度也是7.
data[names == 'Bob']

array([[-0.1284,  0.9638,  2.26  ,  0.7324],
       [-0.8193, -0.4379, -0.4942, -0.8167]])

In [68]:
#mix and match boolean arrays with slices or integers (or sequences of integers, more on this later):
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

array([ 0.7324, -0.8167])

In [70]:
names != 'Bob'
data[-(names == 'Bob')]        # '-',取反

/home/henry/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  from ipykernel import kernelapp as app


array([[-0.3177,  2.3068, -0.5007,  0.1574],
       [ 0.3335,  0.8099, -1.6199,  1.3251],
       [-0.7566, -1.0517,  0.1802,  0.5792],
       [-1.9211, -0.5978, -0.0366,  1.264 ],
       [-1.3856, -1.4865, -1.1779, -1.3247]])

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]       #按顺序选择mark中true所对应的行
data

### Selecting data from an array by boolean indexing always creates a copy of the data even if the returned array is unchanged.

In [75]:
data < 0
data[data < 0] = 0          #data中小于0的元素设为0
data

array([[ 0.    ,  0.9638,  2.26  ,  0.7324],
       [ 0.    ,  2.3068,  0.    ,  0.1574],
       [ 0.3335,  0.8099,  0.    ,  1.3251],
       [ 0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.1802,  0.5792],
       [ 0.    ,  0.    ,  0.    ,  1.264 ],
       [ 0.    ,  0.    ,  0.    ,  0.    ]])

In [78]:
names != 'Joe'
#Setting whole rows or columns using a 1D boolean array
data[names != 'Joe'] = 7
data

array([[ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.    ,  2.3068,  0.    ,  0.1574],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.    ,  0.    ,  0.    ,  1.264 ],
       [ 0.    ,  0.    ,  0.    ,  0.    ]])

### Fancy indexing
### Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
### Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array. 
### Fancy indexing拷贝数据到一个新的数组

In [80]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [81]:
#To select out a subset of the rows in a particular order
#pass a list or ndarray of integers specifying the desired order:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [83]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [85]:
#选择(1,1),(2,2),(3,3),结果还是一维数组
arr[[1,2,3],[1,2,3]]

array([ 1.,  2.,  3.])

In [88]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [91]:
#先按行选择，再对选择的行进行切片以及按列选择
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
#arr[[1, 5, 7, 2]][:, 1: 3]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [93]:
#Another way is to use the np.ix_ function, which converts two 1D integer arrays to an
#indexer that selects the square region:
#选择(1,0),(1,3),(1,1),(1,2),,,,,,,
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing arrays and swapping axes

In [105]:
arr = np.arange(15).reshape((3, 5))
arr
#arr.T


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [104]:
arr.transpose((1,0))

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

In [110]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [111]:
#arr[0][1] <- > arr[1][0]
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [113]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### swapaxes similarly returns a view on the data without making a copy.

In [114]:
#swapaxes takes a pair of axis numbers:
arr.swapaxes(1, 2)       # axis 0 不变

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast element-wise array functions

In [ ]:
arr = np.arange(10)
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = randn(8)
y = randn(8)
x
y
np.maximum(x, y) # element-wise maximum

In [ ]:
arr = randn(7) * 5
np.modf(arr)

## Data processing using arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
from matplotlib.pyplot import imshow, title

In [ ]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

### Expressing conditional logic as array operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = randn(4, 4)
arr
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
# Not to be executed

result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [ ]:
# Not to be executed

np.where(cond1 & cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
# Not to be executed

result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

### Mathematical and statistical methods

In [ ]:
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(0)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)
arr.cumprod(1)

### Methods for boolean arrays

In [ ]:
arr = randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = randn(8)
arr
arr.sort()
arr

In [ ]:
arr = randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and other set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File input and output with arrays

### Storing arrays on disk in binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
!rm some_array.npy
!rm array_archive.npz

### Saving and loading text files

In [ ]:
!cat array_ex.txt

In [ ]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

## Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)  # equivalently np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Random number generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

## Example: Random Walks

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating many random walks at once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))